#!/usr/bin/env node
//
// Static file server for the BetterBash installation tests. It serves the
// directory that ./stage-downloads.sh produced, so the curl, wget and openssl
// methods of getbb.sh talk to the same layout GitHub Pages serves in
// production, dotfiles included.
//
//   node tests/static-server.mjs ROOT HTTP_PORT HTTPS_PORT CERT KEY
//
// Either port may be “-” to serve only the other one. CERT and KEY are required for
// HTTPS and are generated by ./test-install-methods.sh with openssl. Nothing is
// written and no request is logged: this exists to be started and killed inside
// one test run.

import { createServer as httpServer } from 'node:http';
import { createServer as httpsServer } from 'node:https';
import { existsSync, readFileSync, statSync } from 'node:fs';
import { join, normalize, sep } from 'node:path';

const [, , root, httpPort, httpsPort, certFile, keyFile] = process.argv;

if (!root || !httpPort) {
  console.error('usage: static-server.mjs ROOT HTTP_PORT HTTPS_PORT|"-" CERT KEY');
  process.exit(2);
}

const types = {
  '.sh': 'text/plain; charset=utf-8',
  '.html': 'text/html; charset=utf-8',
  '.png': 'image/png',
  '.ico': 'image/x-icon',
};

const serve = (request, response) => {
  // Only files under ROOT, never anything above it.
  const requested = decodeURIComponent((request.url || '/').split('?')[0]);
  const path = normalize(join(root, requested));
  if (!path.startsWith(root + sep)) {
    response.writeHead(404).end('not found\n');
    return;
  }

  if (!existsSync(path) || !statSync(path).isFile()) {
    response.writeHead(404).end('not found\n');
    return;
  }

  const content = readFileSync(path);
  const extension = path.slice(path.lastIndexOf('.') + 1);
  response.writeHead(200, {
    'content-type': types[`.${extension}`] || 'application/octet-stream',
    // A test must never see a cached copy of a file it is about to install.
    'cache-control': 'no-store',
    // Streaming would make node chunk the response, and chunked encoding is not
    // what a static host such as GitHub Pages answers. The openssl install
    // method is exactly about the difference, so the length is stated here.
    'content-length': content.length,
  });
  response.end(content);
};

const listen = (server, port, label) =>
  new Promise((resolve, reject) => {
    server.on('error', reject);
    server.listen(port, '127.0.0.1', () => {
      // Port 0 asks for a free one, so the port that was chosen is what has to
      // be reported to the caller.
      console.log(`listening ${label} 127.0.0.1:${server.address().port}`);
      resolve();
    });
  });

const isRequested = (port) => port !== undefined && port !== null && port !== '' && port !== '-';

const main = async () => {
  if (isRequested(httpPort)) {
    await listen(httpServer(serve), Number(httpPort), 'http');
  }
  if (isRequested(httpsPort)) {
    if (!certFile || !keyFile || !existsSync(certFile) || !existsSync(keyFile)) {
      console.error('https requested without readable certificate and key');
      process.exit(2);
    }
    await listen(
      httpsServer(
        { cert: readFileSync(certFile), key: readFileSync(keyFile) },
        serve,
      ),
      Number(httpsPort),
      'https',
    );
  }
};

main().catch((error) => {
  console.error(`static server failed: ${error.message}`);
  process.exit(1);
});
